### ISSUE TITLE
Missing tailwind CLI install crashes

### ISSUE THREAD

**Issue by paganotoni** [leapkit/template#2]
Recently created project with gonew trows this:

```
~/code/cereme ❯ go run ./cmd/dev 
https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-x64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x100277ec9]

goroutine 7 [running]:
github.com/leapkit/core/gloves.buildWatcher.func1({0xc0001226c8, 0x6}, {0x0?, 0x0?}, {0xc000088f38?, 0xc000120000?})
        /Users/paganotoni/go/pkg/mod/github.com/leapkit/core@v1.2.9/gloves/watcher.go:57 +0x29
path/filepath.walk({0x100709e98, 0x1}, {0x1007f2108, 0xc000120000}, 0xc000088f38)
        /usr/local/go/src/path/filepath/path.go:498 +0x1d5
path/filepath.Walk({0x100709e98, 0x1}, 0xc000076f38)
        /usr/local/go/src/path/filepath/path.go:560 +0x66
github.com/leapkit/core/gloves.buildWatcher({0x0?, 0x0?, 0x0?})
        /Users/paganotoni/go/pkg/mod/github.com/leapkit/core@v1.2.9/gloves/watcher.go:56 +0x97
github.com/leapkit/core/gloves.runWatcher(0xc0000342a0)
        /Users/paganotoni/go/pkg/mod/github.com/leapkit/core@v1.2.9/gloves/watcher.go:16 +0x3e
created by github.com/leapkit/core/gloves.Start in goroutine 1
        /Users/paganotoni/go/pkg/mod/github.com/leapkit/core@v1.2.9/gloves/gloves.go:15 +0x10a
exit status 2
```

**Comment by paganotoni** [comment]
This one is fixed.
